# Filenames are relative to the directory containing the config file.

[server]
# host and port
host = "localhost"
port = 8001
# ssl certificate files, omit for regular http
#ssl_key = "server.key"
#ssl_cert = "server.pem"

[pakhuis]
# sqlite database file
database = "pakhuis.db"

# Poorthuis: authentication
[poorthuis.accounts]
# http basic authentication: username, followed by password hash
# generate hash using: python -m poorthuis
test = "$pbkdf2-sha256$29000$ZkyJcY7xvre2lnJuLSXkvA$boHia0Vck4Z4/hjy4x9QE7lZikv1dHxkD/8B5GMa7p0"
