# Example - copy to "pakhuis-servers.toml"

# sync will use these by default, transfer will use the first by default
default-1 = "localhost"
default-2 = "remote"

[servers.localhost]
# Pakhuis url
url = "https://localhost:8001/"
# Username on the server (will ask when omitted)
username = "abc123"
# Password for the server (will ask when omitted)
# password = "abc123"

[servers.remote]
url = "https://remote.host:8001/"
username = "def456"
# password = "def456"
